#!/bin/sh

case "$1" in
  start)
    echo "Starting kiosk..."
    /usr/bin/kiosk.sh &
    ;;
  stop)
    killall kiosk-clock 2>/dev/null || true
    killall weston 2>/dev/null || true
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0